// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaperCache.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PaperCache.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace GameProto {

namespace {

const ::google::protobuf::Descriptor* PaperCache_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PaperCache_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PaperCache_2eproto() {
  protobuf_AddDesc_PaperCache_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PaperCache.proto");
  GOOGLE_CHECK(file != NULL);
  PaperCache_descriptor_ = file->message_type(0);
  static const int PaperCache_offsets_[1] = {
  };
  PaperCache_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PaperCache_descriptor_,
      PaperCache::default_instance_,
      PaperCache_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PaperCache, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PaperCache, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PaperCache));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PaperCache_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PaperCache_descriptor_, &PaperCache::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PaperCache_2eproto() {
  delete PaperCache::default_instance_;
  delete PaperCache_reflection_;
}

void protobuf_AddDesc_PaperCache_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020PaperCache.proto\022\tGameProto\"\014\n\nPaperCa"
    "che", 43);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PaperCache.proto", &protobuf_RegisterTypes);
  PaperCache::default_instance_ = new PaperCache();
  PaperCache::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PaperCache_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PaperCache_2eproto {
  StaticDescriptorInitializer_PaperCache_2eproto() {
    protobuf_AddDesc_PaperCache_2eproto();
  }
} static_descriptor_initializer_PaperCache_2eproto_;

// ===================================================================

#ifndef _MSC_VER
#endif  // !_MSC_VER

PaperCache::PaperCache()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void PaperCache::InitAsDefaultInstance() {
}

PaperCache::PaperCache(const PaperCache& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void PaperCache::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PaperCache::~PaperCache() {
  SharedDtor();
}

void PaperCache::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PaperCache::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PaperCache::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PaperCache_descriptor_;
}

const PaperCache& PaperCache::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PaperCache_2eproto();
  return *default_instance_;
}

PaperCache* PaperCache::default_instance_ = NULL;

PaperCache* PaperCache::New() const {
  return new PaperCache;
}

void PaperCache::Clear() {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PaperCache::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
        ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
      return true;
    }
    DO_(::google::protobuf::internal::WireFormat::SkipField(
          input, tag, mutable_unknown_fields()));
  }
  return true;
#undef DO_
}

void PaperCache::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* PaperCache::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int PaperCache::ByteSize() const {
  int total_size = 0;

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PaperCache::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PaperCache* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PaperCache*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PaperCache::MergeFrom(const PaperCache& from) {
  GOOGLE_CHECK_NE(&from, this);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PaperCache::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PaperCache::CopyFrom(const PaperCache& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PaperCache::IsInitialized() const {

  return true;
}

void PaperCache::Swap(PaperCache* other) {
  if (other != this) {
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PaperCache::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PaperCache_descriptor_;
  metadata.reflection = PaperCache_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace GameProto

// @@protoc_insertion_point(global_scope)
